### ISSUE TITLE
Как запаковать веб-приложение в один файл?

### ISSUE THREAD

**Issue by romanvolodin** [opennota/tl#1]
Узнал про проект на ЛОРе. Других способов связаться не нашел, по этому пишу здесь.
Собственно, меня интересует как запаковать веб-приложение в один файл?
Увидел тут - https://github.com/opennota/tl/releases/tag/v1.0.4, очень понравилось.
Это фича Go или можно любое приложение так запаковать?
Что писать в Гугле, чтобы научиться?

**Comment by opennota** [comment]
В Go это сделать проще, потому что компилятор создаёт статически слинкованные бинарники. Остаётся только включить туда же ресурсы (JS, CSS, HTML и т.д.). Я использую https://github.com/mjibson/esc

**Comment by opennota** [comment]
Можно погуглить `single binary web app` или `self-contained web app`. Для node.js нашлось такое: https://github.com/nexe/nexe
